version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: babel-plugin-emotion
    versions:
    - "> 9.2.11"
  - dependency-name: typescript
    versions:
    - "> 3.2.4"
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: element-ui
    versions:
    - 2.14.1
    - 2.15.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: elliptic
    versions:
    - 6.5.3
